server:
  port: 8782

spring:
    application:
      name: bytetcc-provider
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            url: jdbc:mysql://172.16.154.26:3306/test_dist?useUnicode=true&characterEncoding=utf-8
            #url: jdbc:mysql://127.0.0.1:3306/product?useSSL=true
            username: root
            password: imsp_vcloud
            #password: cll123456

            initial-size: 2
            max-active: 10
            min-idle: 2
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8717/eureka



feign:
  hystrix:
    enabled: true

# 关于springcloud-hystrix机制 http://www.jianshu.com/p/b8d21248c9b1
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000


#Ribbon的负载均衡策略
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

