server:
  port: 8881

spring:
    application:
      name: message-consumer

    rabbitmq:
      addresses: 127.0.0.1:5672
      username: guest
      password: guest



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8717/eureka




